### ISSUE TITLE
make index-elasticsearch fails

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/next-sc#383]
This has worked for me in the past, but running the following commands in the `next-sc` directory gave me the stack trace below.

```
git pull
sudo make prepare-host
sudo make build-all
sudo make load-data
sudo make run-dev-no-logs
sudo make load-data
sudo make index-elasticsearch
```

```
 26% 11/42 [05:56<08:18, 16.08s/it]INFO:search.indexer:Creating index lzh_c7be29301c because index does not exists
INFO:search.indexer:Creating index named lzh_c7be29301c, alias lzh
Traceback (most recent call last):
  File "manage.py", line 70, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 54, in index_elasticsearch
    update()
  File "/opt/sc/sc-flask/server/search/texts.py", line 211, in update
    indexer.update()
  File "/opt/sc/sc-flask/server/search/indexer.py", line 232, in update
    self.update_data()
  File "/opt/sc/sc-flask/server/search/texts.py", line 193, in update_data
    self.process_chunks(chunks)
  File "/opt/sc/sc-flask/server/search/indexer.py", line 250, in process_chunks
    for chunk in chunks:
  File "/opt/sc/sc-flask/server/search/texts.py", line 115, in yield_docs_from_dir
    for i, text in enumerate(html_texts):
  File "/usr/local/lib/python3.6/site-packages/arango/cursor.py", line 32, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/site-packages/arango/cursor.py", line 124, in next
    raise CursorNextError(res)
arango.exceptions.CursorNextError: [HTTP 404][ERR 1600] cursor not found
Makefile:169: recipe for target 'index-elasticsearch' failed
make: *** [index-elasticsearch] Error 1
```

**Comment by TrebuhD** [comment]
This error usually occurs when there's not enough available RAM on the system to complete the elasticsearch indexing process. Try to close Chrome or other RAM-intensive programs while running the last command.

**Comment by jhanarato** [comment]
Just ran the command again with no problems.

Thanks!
